/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "FinancialResearchAgent";
	}
	interface Env {
		AI: Ai;
		/** Cloudflare Browser Rendering binding (Puppeteer) */
		BROWSER: Fetcher;
		/** Financial Modeling Prep API key — free tier at financialmodelingprep.com */
		FMP_API_KEY: string;
		FinancialResearchAgent: DurableObjectNamespace<import("./src/server").FinancialResearchAgent>;
	}
}
interface Env extends Cloudflare.Env {}
