/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 75d4d4557837b3067f82201813b3ee94)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "FinancialResearchAgent";
	}
	interface Env {
		AI: Ai;
		POLYGON_API_KEY: "";
		FinancialResearchAgent: DurableObjectNamespace<import("./src/server").FinancialResearchAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "POLYGON_API_KEY">> {}
}
